config/routes.rb
Rails.application.routes.draw do
  post "api/slack/command", to: "slack_commands#slash_command"
  post "api/slack/action", to: "slack_actions#view_submission"
  get "api/auth/", to: "auth#finish_auth"

  resources :pages
  root to: "pages#index"
end

app/views/pages/index.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-sm-10">
        <h1 class="text-center mb-4">Incidents</h1>
    </div>
    <div class="col-sm-2">
        <a target="_self" class="c-link" href="https://slack.com/oauth/v2/authorize?client_id=4267771546337.5069536335234&amp;scope=channels:read,chat:write,commands,groups:read,incoming-webhook,users:read,channels:manage&amp;user_scope=" rel="noopener noreferrer"><img alt="Add to Slack" height="40" width="139" src="https://platform.slack-edge.com/img/add_to_slack.png" srcset="https://platform.slack-edge.com/img/add_to_slack.png 1x, https://platform.slack-edge.com/img/add_to_slack@2x.png 2x"></a>
    </div>
  </div>
  <% if @incidents.present? %>
    <% @incidents.each do |incident| %>
        <div class="card m-3" >
            <div class="card-header">
                <div class="row">
                    <div class="col-sm-10">
                        <p class="text-primary h3"><%= incident.title %></p>
                    </div>
                    <div class="col-sm-2 d-flex align-items-center justify-content-center">
                        <p class="text-light p-2 <%= incident.resolved == 0 ? "bg-primary" : "bg-success" %> h5 rounded">
                            <%= incident.resolved == 0 ? "Opened" : "Resolved" %>
                        </p>
                        <%# <%= link_to "Delete", pages_path(incident), method: :delete, data: { confirm: "Are you sure?" } %>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-sm-8">
                        <p class="h6"><%= incident.description %></p>
                        <span class="badge <%= 
                            incident.severity == 'SEV-0' ? 'bg-sev0' : 
                            incident.severity == 'SEV-1' ? 'bg-sev1' : 
                            incident.severity == 'SEV-2' ? 'bg-sev2' : 
                            'bg-sev3' %>"><%= incident.severity %></span>
                    </div>
                    <div class="col-sm-4">
                        <p class="h4"><%= incident.created_by %></p>
                        <p class="h6"><%= incident.created_at.strftime('%Y-%m-%d %H:%M:%S') %> (Opened)</p>
                        <% if incident.resolved? %>
                            <% solving_time = distance_of_time_in_words(incident.created_at, incident.resolved_at) %>
                            <p class="h6"><%= incident.resolved_at.strftime('%Y-%m-%d %H:%M:%S') %> (Solved - <%= solving_time %> later)</p>
                        <% end %>
                    </div>

                </div>
            </div>
        </div>
    <% end %>  
  <% end %>
</div>